
FROM node:18-alpine AS build

WORKDIR /app


COPY angular/package*.json ./
RUN npm install


COPY angular/ ./

RUN npm run build


FROM node:18

WORKDIR /app


COPY --from=build /app/dist/angular /app


RUN npm install -g http-server

EXPOSE 3000

CMD ["http-server", "/app/browser", "-p", "3000"]