
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
      # - ./init_user_collection.js:/docker-entrypoint-initdb.d/init_user_collection.js
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

     

  server:
    build:
      context: ./server 
      dockerfile: ./DockerFile
    container_name: python-server
    ports:
      - "8000:8000" 
    volumes:
      - ./Server/app:/app 
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/mydatabase
    depends_on:
      - mongodb 


  client:
    build:
      context: ./client
      dockerfile: DockerFile
    container_name: frontend-client
    ports:
      - "4200:4200"
    depends_on:
      - server
volumes:
  mongo-data:
    driver: local 