
services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      # - ./init_user_collection.js:/docker-entrypoint-initdb.d/init_user_collection.js
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

     

  # Python Server Service
  server:
    build:
      context: ./server # Path to your server folder
      dockerfile: ./DockerFile
    container_name: python-server
    ports:
      - "5000:5000" # Maps the server port
    environment:
      - MONGO_URI=mongodb://root:password@mongo:27017/mydatabase
    depends_on:
      - mongodb # Ensures server waits for MongoDB to start

  # Frontend Client Service
  client:
    build:
      context: ./client # Path to your client folder
      dockerfile: DockerFile
    container_name: frontend-client
    ports:
      - "3000:3000" # Maps the client port
    depends_on:
      - server # Ensures client waits for the server to start 
volumes:
  mongo-data:
    driver: local  
