# Use the official Python image from Docker Hub
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /appD

# Set PYTHONPATH to include /appD
ENV PYTHONPATH=/appD

# Copy the requirements file into the container
COPY requirements.txt .

# Install the dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org

# Copy the application code into the container
COPY ./appD /appD

# Expose the port the app runs on
EXPOSE 8000

# Define the command to run the application
CMD ["uvicorn", "appD.app:app", "--host", "0.0.0.0", "--port", "8000"]